import { usePDF } from '#pdf'
import LetterTemplate from '../../components/pdf/LetterTemplate.vue'

export default defineEventHandler(async (event) => {
  const { sendPDF } = usePDF()
  return sendPDF(event, LetterTemplate, {
    company: 'Sidebase GmbH',
    recipient: 'John Doe\nAcme Corp\n456 Oak Avenue\n67890 Metropolis',
    subject: 'DIN 676 Letter Template Demo',
    body: 'This is a demonstration of the DIN 676 Form B letter template generated by @sidebase/nuxt-pdf.\n\nThe letter layout follows the DIN 676 standard with proper zones for letterhead, logo, address, reference information, and content.\n\nAll zones are positioned according to the specification, including the 45mm letterhead area, 85x45mm recipient window, and fold marks at the standard positions.',
  }, { filename: 'letter.pdf' })
})
