export type { ModuleOptions, RenderOptions, SendPDFOptions, ComponentProps } from './types'
export type { ASize, AnySize, DebugMode, MarkerMode, PDFWrapperProps } from './components/types'
export { PDFError } from './errors'
export type { PDFErrorCode } from './errors'
export { default as PDFWrapper } from './components/PDFWrapper.vue'
export { default as LetterA } from './components/base/LetterA.vue'
export { default as LetterB } from './components/base/LetterB.vue'
export { default as Image } from './components/utils/Image.vue'
export { default as Footer } from './components/utils/Footer.vue'
export { default as FoldMarksA } from './components/utils/FoldMarksA.vue'
export { default as FoldMarksB } from './components/utils/FoldMarksB.vue'
