export type { ModuleOptions, RenderOptions, SendPDFOptions, ComponentProps } from './types'
export type { ASize, AnySize, DebugMode, MarkerMode, PDFWrapperProps } from './components/types'
export { PDFError } from './errors'
export type { PDFErrorCode } from './errors'
export { default as PDFWrapper } from './components/PDFWrapper.vue'
export { default as Image } from './components/utils/Image.vue'
