import { defineEventHandler } from 'h3'
import { defineComponent, h } from 'vue'

const TestTemplate = defineComponent({
  props: {
    title: { type: String, default: 'Test PDF' },
  },
  setup(props) {
    return () => h('div', { class: 'p-8' }, [
      h('h1', { class: 'text-2xl font-bold' }, props.title),
      h('p', { class: 'mt-4 text-gray-600' }, 'Generated by test fixture'),
    ])
  },
})

export default defineEventHandler(async (event) => {
  const { usePDF } = await import('#pdf')
  const { sendPDF } = usePDF()
  return sendPDF(event, TestTemplate, { title: 'E2E Test' }, {
    filename: 'test.pdf',
    usePagedJS: false,
  })
})
