<script setup lang="ts">
defineProps<{ title: string }>()
</script>

<template>
  <div class="p-8">
    <h1 class="text-2xl font-bold text-blue-600">{{ title }}</h1>
    <p class="mt-4 text-gray-700">This is a basic PDF generated by @sidebase/nuxt-pdf.</p>
  </div>
</template>
